### ISSUE TITLE
RunAtacAnnoR stop at  97%

### ISSUE THREAD

**Issue by WeiFeng0726** [TianLab-Bioinfo/AtacAnnoR#1]
RunAtacAnnoR/RunAtacAnnoR_Signac process stops at 97% and becomes unresponsive without error  message, successful runs occurring only in extremely rare instances.

I have to try step_by_step_v2  and it stops at get_seed_candidates 93%

**Comment by Telogen** [comment]
Thanks for using AtacAnnoR! If the program got stuck in get_seed_candidates(), you can save your input `cell_meta` as `.RDS` file and sent it to my email: ljtian20@fudan.edu.cn. I will try my best to find out where the problem lies.

**Comment by WeiFeng0726** [comment]
> 感谢您使用AtacAnnoR！如果程序卡在 get_seed_candidates（） 中，您可以将您的输入保存为文件并将其发送到我的电子邮件：[ljtian20@fudan.edu.cn](mailto:ljtian20@fudan.edu.cn)。我会尽我所能找出问题所在。`cell_meta``.RDS`

I solved this problem, AtacAnnoR seems to conflict with the following packages:
library(GenomicRanges)
library(S4Vectors)
gr <- GRanges(seqnames = "chr1", ranges = IRanges(start = c(20, 70, 300), end = c(120, 200, 400)))
library(Signac)
library(Seurat)
library(GenomicRanges)
library(future)
library(AtacAnnoR)
plan("multicore", workers = 4)
options(future.globals.maxSize = 50000 * 1024^2)
library(harmony)
library(EnsDb.Mmusculus.v79)


if i just library  AtacAnnoR, Signac, Seurat, AtacAnnoR works fine
